### ISSUE TITLE
FindIntegrationAnchors throws Error in SetAssayData.ChromatinAssay

### ISSUE THREAD

**Issue by justin-malin** [timoast/signac#262]
Hi Tim,

I'm getting the following error running FindIntegration Anchors. 
```

> anchors <- FindIntegrationAnchors(
+   object.list = list(pbmc.1.filtered, pbmc.2.filtered),
+   anchor.features = shared.features,
+   assay = c('peaks','peaks'),
+   k.filter = NA
+ )
Scaling features for provided objects
  |                                                  | 0 % ~calculating  Error in SetAssayData.ChromatinAssay(object = object, slot = "scale.data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object
```

I've read related posts eg https://github.com/timoast/signac/issues/230 https://github.com/timoast/signac/issues/251  but haven't found any recommended fixes that work for me.

This is the code I'm running. (For the purpose of debugging, I'm using just the first 10k features from the reduced peak set 'all.peaks')

```
gr1 <- StringToGRanges(regions = rownames(pbmc.1.filtered), sep = c("-","-"))
gr2 <- StringToGRanges(regions = rownames(pbmc.2.filtered), sep = c("-","-"))

all.peaks <- reduce(c(gr1, gr2), ignore.strand=TRUE)

fragment.path <- '~/Desktop/ATAC-Seq_data/fragments_prefixed_all.tsv.gz'
fragments <- CreateFragmentObject(
  path = fragment.path,
  cells = c(colnames(pbmc.1.filtered), colnames(pbmc.2.filtered)),
  validate.fragments = TRUE
)

peaks_pbmc.1.filtered <- FeatureMatrix(
  fragments = fragments,
  features = all.peaks[1:10000],
  cells = colnames(pbmc.1.filtered)
)
peaks_pbmc.2.filtered <- FeatureMatrix(
  fragments = fragments,
  features = all.peaks[1:10000],
  cells = colnames(pbmc.2.filtered)
)

pbmc.1.filtered[['peaks']] <- CreateChromatinAssay(counts = peaks_pbmc.1.filtered, genome = "mm10")
pbmc.2.filtered[['peaks']] <- CreateChromatinAssay(counts = peaks_pbmc.2.filtered, genome = "mm10")

pbmc.1.filtered <- RunTFIDF(pbmc.1.filtered, assay='peaks')
pbmc.1.filtered <- FindTopFeatures(pbmc.1.filtered, min.cutoff = 50)
pbmc.1.filtered <- RunSVD(pbmc.1.filtered)
pbmc.1.filtered <- RunUMAP(pbmc.1.filtered, reduction = 'lsi', dims = 2:30)

pbmc.2.filtered <- RunTFIDF(pbmc.2.filtered, assay='peaks')
pbmc.2.filtered <- FindTopFeatures(pbmc.2.filtered, min.cutoff = 50)
pbmc.2.filtered <- RunSVD(pbmc.2.filtered)
pbmc.2.filtered <- RunUMAP(pbmc.2.filtered, reduction = 'lsi', dims = 2:30)

shared.features <- intersect(rownames(pbmc.1.filtered), rownames(pbmc.2.filtered))

anchors <- FindIntegrationAnchors(
  object.list = list(pbmc.1.filtered, pbmc.2.filtered),
  anchor.features = shared.features,
  assay = c('peaks', 'peaks'),
  k.filter = NA
)
```
Below is the traceback from the error:
```
> traceback()
11: stop("Number of rows in provided matrix does not match\n           the number of rows in the object")
10: SetAssayData.ChromatinAssay(object = object, slot = "scale.data", 
        new.data = ScaleData(object = GetAssayData(object = object, 
            slot = slot.use), features = features, vars.to.regress = vars.to.regress, 
            latent.data = latent.data, split.by = split.by, model.use = model.use, 
            use.umi = use.umi, do.scale = do.scale, do.center = do.center, 
            scale.max = scale.max, block.size = block.size, min.cells.to.block = min.cells.to.block, 
            verbose = verbose, ...))
9: SetAssayData(object = object, slot = "scale.data", new.data = ScaleData(object = GetAssayData(object = object, 
       slot = slot.use), features = features, vars.to.regress = vars.to.regress, 
       latent.data = latent.data, split.by = split.by, model.use = model.use, 
       use.umi = use.umi, do.scale = do.scale, do.center = do.center, 
       scale.max = scale.max, block.size = block.size, min.cells.to.block = min.cells.to.block, 
       verbose = verbose, ...))
8: ScaleData.Assay(object = assay.data, features = features, vars.to.regress = vars.to.regress, 
       latent.data = latent.data, split.by = split.by, model.use = model.use, 
       use.umi = use.umi, do.scale = do.scale, do.center = do.center, 
       scale.max = scale.max, block.size = block.size, min.cells.to.block = min.cells.to.block, 
       verbose = verbose, ...)
7: ScaleData(object = assay.data, features = features, vars.to.regress = vars.to.regress, 
       latent.data = latent.data, split.by = split.by, model.use = model.use, 
       use.umi = use.umi, do.scale = do.scale, do.center = do.center, 
       scale.max = scale.max, block.size = block.size, min.cells.to.block = min.cells.to.block, 
       verbose = verbose, ...)
6: ScaleData.Seurat(object = object, features = anchor.features, 
       verbose = FALSE)
5: ScaleData(object = object, features = anchor.features, verbose = FALSE)
4: FUN(X[[i]], ...)
3: lapply(X[Split[[i]]], FUN, ...)
2: my.lapply(X = object.list, FUN = function(object) {
       ScaleData(object = object, features = anchor.features, verbose = FALSE)
   })
1: FindIntegrationAnchors(object.list = list(pbmc.1.filtered, pbmc.2.filtered), 
       anchor.features = shared.features, assay = c("peaks", "peaks"), 
       k.filter = NA)
```
I'd love some insight into what's causing the problem.

Thanks so much,
Justin

**Comment by timoast** [comment]
This should be fixed on the develop branch. Can you install from the develop branch and try again?

**Comment by justin-malin** [comment]
To answer your question with a question, have you come across the following error when trying to install from development branch?
```
> install("timoast/signac")
Error: Can't find 'timoast/signac'.
> install_github("timoast/signac")
Downloading GitHub repo timoast/signac@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: data.table (1.12.8 -> 1.13.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
data.table (1.12.8 -> 1.13.0) [CRAN]
Skipping 12 packages not available: qvalue, AnnotationFilter, biovizBase, ggbio, Biostrings, BiocGenerics, Biobase, S4Vectors, Rsamtools, IRanges, GenomicRanges, GenomeInfoDb
Installing 1 packages: data.table

  There is a binary version available but the source
  version is later:
           binary source needs_compilation
data.table 1.12.8 1.13.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source package ‘data.table’

trying URL 'https://cran.rstudio.com/src/contrib/data.table_1.13.0.tar.gz'
Content type 'application/x-gzip' length 5273400 bytes (5.0 MB)
==================================================
downloaded 5.0 MB

* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
*** pkg-config is not installed.
*** Compilation will now be attempted and if it works you can ignore this message. However,
*** if compilation fails, try 'locate zlib.h zconf.h' and ensure the zlib development library
*** is installed :
***   deb: zlib1g-dev (Debian, Ubuntu, ...)
***   rpm: zlib-devel (Fedora, EPEL, ...)
***   brew: zlib (OSX)
*** Note that zlib is required to compile R itself so you may find the advice in the R-admin
*** guide helpful regarding zlib. On Debian/Ubuntu, zlib1g-dev is a dependency of r-base as
*** shown by 'apt-cache showsrc r-base | grep ^Build-Depends | grep zlib', and therefore
*** 'sudo apt-get build-dep r-base' should be sufficient too.
*** To silence this message, please ensure that :
***   1) 'pkg-config --exists zlib' succeeds (i.e. $? -eq 0)
***   2) 'pkg-config --libs zlib' contains -lz
*** Compilation will now be attempted ...
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c assign.c -o assign.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c between.c -o between.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c bmerge.c -o bmerge.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c chmatch.c -o chmatch.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c cj.c -o cj.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c coalesce.c -o coalesce.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c dogroups.c -o dogroups.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fastmean.c -o fastmean.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fcast.c -o fcast.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fifelse.c -o fifelse.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fmelt.c -o fmelt.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c forder.c -o forder.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c frank.c -o frank.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fread.c -o fread.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c freadR.c -o freadR.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c froll.c -o froll.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c frollR.c -o frollR.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c frolladaptive.c -o frolladaptive.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fsort.c -o fsort.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fwrite.c -o fwrite.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fwriteR.c -o fwriteR.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c gsumm.c -o gsumm.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ijoin.c -o ijoin.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c inrange.c -o inrange.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c nafill.c -o nafill.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c nqrecreateindices.c -o nqrecreateindices.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c openmp-utils.c -o openmp-utils.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c quickselect.c -o quickselect.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c rbindlist.c -o rbindlist.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c reorder.c -o reorder.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c shift.c -o shift.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c snprintf.c -o snprintf.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c subset.c -o subset.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c transpose.c -o transpose.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c types.c -o types.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c uniqlist.c -o uniqlist.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c utils.c -o utils.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c vecseq.c -o vecseq.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c wrappers.c -o wrappers.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o data.table.so assign.o between.o bmerge.o chmatch.o cj.o coalesce.o dogroups.o fastmean.o fcast.o fifelse.o fmelt.o forder.o frank.o fread.o freadR.o froll.o frollR.o frolladaptive.o fsort.o fwrite.o fwriteR.o gsumm.o ijoin.o init.o inrange.o nafill.o nqrecreateindices.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o snprintf.o subset.o transpose.o types.o uniqlist.o utils.o vecseq.o wrappers.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-data.table/00new/data.table/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘data.table’ in library.dynam(lib, package, package.lib):
 shared object ‘datatable.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status
```

**Comment by justin-malin** [comment]
After updating using the developmental branch, I'm still getting the following:

```
> anchors <- FindIntegrationAnchors(
+   object.list = list(pbmc.1.filtered, pbmc.2.filtered),
+   anchor.features = shared.features,
+   assay = c('peaks','peaks'),
+   k.filter = NA
+ )
Scaling features for provided objects
  |                                                  | 0 % ~calculating  Error in SetAssayData.ChromatinAssay(object = object, slot = "scale.data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object
```

**Comment by timoast** [comment]
Can you post the output of `sessionInfo()`?

**Comment by justin-malin** [comment]
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] grid      splines   tools     stats4    parallel  stats    
 [7] graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] regioneR_1.16.5                         
 [2] Rsamtools_2.0.3                         
 [3] TxDb.Mmusculus.UCSC.mm10.knownGene_3.4.7
 [4] universalmotif_1.2.1                    
 [5] chromVAR_1.6.0                          
 [6] cicero_1.2.0                            
 [7] Gviz_1.28.3                             
 [8] monocle_2.12.0                          
 [9] DDRTree_0.1.5                           
[10] irlba_2.3.3                             
[11] VGAM_1.1-3                              
[12] stringr_1.4.0                           
[13] cowplot_1.1.0                           
[14] reshape2_1.4.4                          
[15] tidyr_1.1.2                             
[16] pheatmap_1.0.12                         
[17] dplyr_1.0.2                             
[18] Matrix_1.2-18                           
[19] ggplot2_3.3.2                           
[20] EnsDb.Mmusculus.v79_2.99.0              
[21] ensembldb_2.8.1                         
[22] AnnotationFilter_1.8.0                  
[23] GenomicFeatures_1.36.4                  
[24] AnnotationDbi_1.48.0                    
[25] Biobase_2.46.0                          
[26] BSgenome.Mmusculus.UCSC.mm10_1.4.0      
[27] BSgenome_1.52.0                         
[28] rtracklayer_1.44.4                      
[29] Biostrings_2.52.0                       
[30] XVector_0.26.0                          
[31] GenomicRanges_1.38.0                    
[32] GenomeInfoDb_1.22.1                     
[33] IRanges_2.20.2                          
[34] S4Vectors_0.24.4                        
[35] BiocGenerics_0.32.0                     
[36] TFBSTools_1.22.0                        
[37] JASPAR2018_1.1.1                        
[38] Seurat_3.2.2                            
[39] Signac_1.0.0                            
[40] devtools_2.3.2                          
[41] usethis_1.6.3                           

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.1              SnowballC_0.7.0            
  [3] GGally_2.0.0                R.methodsS3_1.8.1          
  [5] bit64_4.0.2                 knitr_1.29                 
  [7] DelayedArray_0.12.3         R.utils_2.9.2              
  [9] data.table_1.12.8           rpart_4.1-15               
 [11] KEGGREST_1.24.1             RCurl_1.98-1.2             
 [13] generics_0.0.2              callr_3.4.4                
 [15] RSQLite_2.2.0               combinat_0.0-8             
 [17] RANN_2.6.1                  future_1.19.1              
 [19] bit_4.0.4                   spatstat.data_1.4-3        
 [21] httpuv_1.5.4                SummarizedExperiment_1.16.1
 [23] assertthat_0.2.1            DirichletMultinomial_1.26.0
 [25] viridis_0.5.1               xfun_0.16                  
 [27] hms_0.5.3                   promises_1.1.1             
 [29] fansi_0.4.1                 progress_1.2.2             
 [31] caTools_1.18.0              igraph_1.2.5               
 [33] DBI_1.1.0                   htmlwidgets_1.5.1          
 [35] sparsesvd_0.2               reshape_0.8.8              
 [37] purrr_0.3.4                 ellipsis_0.3.1             
 [39] RSpectra_0.16-0             backports_1.1.10           
 [41] gbRd_0.4-11                 annotate_1.64.0            
 [43] biomaRt_2.40.5              deldir_0.1-29              
 [45] vctrs_0.3.4                 remotes_2.2.0              
 [47] ROCR_1.0-11                 abind_1.4-5                
 [49] withr_2.3.0                 checkmate_2.0.0            
 [51] sctransform_0.3             treeio_1.8.2               
 [53] GenomicAlignments_1.20.1    prettyunits_1.1.1          
 [55] goftest_1.2-2               cluster_2.1.0              
 [57] ape_5.4-1                   lazyeval_0.2.2             
 [59] seqLogo_1.50.0              crayon_1.3.4               
 [61] slam_0.1-47                 pkgconfig_2.0.3            
 [63] nlme_3.1-149                pkgload_1.1.0              
 [65] ProtGenerics_1.16.0         nnet_7.3-14                
 [67] rlang_0.4.7                 globals_0.13.0             
 [69] lifecycle_0.2.0             miniUI_0.1.1.1             
 [71] rsvd_1.0.3                  dichromat_2.0-0            
 [73] rprojroot_1.3-2             polyclip_1.10-0            
 [75] matrixStats_0.57.0          lmtest_0.9-38              
 [77] graph_1.64.0                ggseqlogo_0.1              
 [79] zoo_1.8-8                   base64enc_0.1-3            
 [81] ggridges_0.5.2              processx_3.4.4             
 [83] png_0.1-7                   viridisLite_0.3.0          
 [85] bitops_1.0-6                R.oo_1.24.0                
 [87] KernSmooth_2.23-17          blob_1.2.1                 
 [89] qvalue_2.16.0               readr_1.3.1                
 [91] jpeg_0.1-8.1                CNEr_1.20.0                
 [93] scales_1.1.1                memoise_1.1.0              
 [95] magrittr_1.5                plyr_1.8.6                 
 [97] ica_1.0-2                   bibtex_0.4.2.2             
 [99] zlibbioc_1.32.0             HSMMSingleCell_1.4.0       
[101] compiler_3.6.3              RColorBrewer_1.1-2         
[103] fitdistrplus_1.1-1          cli_2.0.2                  
[105] listenv_0.8.0               patchwork_1.0.1            
[107] pbapply_1.4-3               ps_1.3.4                   
[109] htmlTable_2.0.1             Formula_1.2-3              
[111] MASS_7.3-52                 mgcv_1.8-32                
[113] tidyselect_1.1.0            stringi_1.5.3              
[115] densityClust_0.3            yaml_2.2.1                 
[117] latticeExtra_0.6-29         ggrepel_0.8.2              
[119] VariantAnnotation_1.30.1    fastmatch_1.1-0            
[121] future.apply_1.6.0          rstudioapi_0.11            
[123] TFMPvalue_0.0.8             foreign_0.8-75             
[125] lsa_0.73.2                  gridExtra_2.3              
[127] Rtsne_0.15                  rvcheck_0.1.8              
[129] digest_0.6.25               BiocManager_1.30.10        
[131] FNN_1.1.3                   shiny_1.5.0                
[133] pracma_2.2.9                qlcMatrix_0.9.7            
[135] Rcpp_1.0.5                  later_1.1.0.1              
[137] RcppAnnoy_0.0.16            OrganismDbi_1.26.0         
[139] httr_1.4.2                  ggbio_1.32.0               
[141] biovizBase_1.32.0           Rdpack_1.0.0               
[143] colorspace_1.4-1            XML_3.99-0.3               
[145] fs_1.5.0                    tensor_1.5                 
[147] reticulate_1.16             uwot_0.1.8                 
[149] RBGL_1.60.0                 RcppRoll_0.3.0             
[151] tidytree_0.3.3              spatstat.utils_1.17-0      
[153] plotly_4.9.2.1              sessioninfo_1.1.1          
[155] xtable_1.8-4                ggtree_1.16.6              
[157] jsonlite_1.7.1              poweRlaw_0.70.6            
[159] spatstat_1.64-1             testthat_2.3.2             
[161] R6_2.4.1                    Hmisc_4.4-1                
[163] pillar_1.4.6                htmltools_0.5.0            
[165] mime_0.9                    DT_0.15                    
[167] glue_1.4.2                  fastmap_1.0.1              
[169] BiocParallel_1.20.1         codetools_0.2-16           
[171] pkgbuild_1.1.0              lattice_0.20-41            
[173] tibble_3.0.3                curl_4.3                   
[175] leiden_0.3.3                gtools_3.8.2               
[177] GO.db_3.8.2                 limma_3.40.6               
[179] survival_3.2-3              docopt_0.7.1               
[181] fastICA_1.2-2               desc_1.2.0                 
[183] munsell_0.5.0               GenomeInfoDbData_1.2.2     
[185] gtable_0.3.0 
```

**Comment by timoast** [comment]
The sessionInfo shows you still have the current release version loaded, not the develop version. Please install the develop version and verify that it's loaded by looking at the output of `packageVersion("Signac")` (should be 1.0.9001)

**Comment by justin-malin** [comment]
Not sure why, but even though it seems to install without error, it still says version 1.0.0

```
> remove.packages('Signac')
Removing package from '/Library/Frameworks/R.framework/Versions/3.6/Resources/library'
(as 'lib' is unspecified)
> install_github('timoast/signac')
Downloading GitHub repo timoast/signac@HEAD
Skipping 12 packages not available: qvalue, AnnotationFilter, biovizBase, ggbio, Biostrings, BiocGenerics, Biobase, S4Vectors, Rsamtools, IRanges, GenomicRanges, GenomeInfoDb
✓  checking for file ‘/private/var/folders/tc/3kzjyz5d7qv7j1jxsjyn51_d9hfby7/T/RtmpCYutCD/remotes162aa2e1a8e55/timoast-signac-c53f270/DESCRIPTION’ (443ms)
─  preparing ‘Signac’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘Signac/.github’
   Removed empty directory ‘Signac/vignettes’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘Signac_1.0.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘Signac’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c filter.cpp -o filter.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c group.cpp -o group.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c validate.cpp -o validate.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Signac.so RcppExports.o filter.o group.o validate.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Signac/00new/Signac/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: multiple methods tables found for ‘type’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘GenomicAlignments’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘BSgenome’
Warning: replacing previous import ‘GenomicRanges::.__C__GenomicRanges_OR_GenomicRangesList’ by ‘rtracklayer::.__C__GenomicRanges_OR_GenomicRangesList’ when loading ‘BSgenome’
No methods found in package ‘IRanges’ for request: ‘splitAsList’ when loading ‘ensembldb’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: multiple methods tables found for ‘type’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘GenomicAlignments’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘BSgenome’
Warning: replacing previous import ‘GenomicRanges::.__C__GenomicRanges_OR_GenomicRangesList’ by ‘rtracklayer::.__C__GenomicRanges_OR_GenomicRangesList’ when loading ‘BSgenome’
No methods found in package ‘IRanges’ for request: ‘splitAsList’ when loading ‘ensembldb’
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Warning: multiple methods tables found for ‘type’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘GenomicAlignments’
Warning: replacing previous import ‘BiocGenerics::type’ by ‘Biostrings::type’ when loading ‘BSgenome’
Warning: replacing previous import ‘GenomicRanges::.__C__GenomicRanges_OR_GenomicRangesList’ by ‘rtracklayer::.__C__GenomicRanges_OR_GenomicRangesList’ when loading ‘BSgenome’
No methods found in package ‘IRanges’ for request: ‘splitAsList’ when loading ‘ensembldb’
** testing if installed package keeps a record of temporary installation path
* DONE (Signac)
> library(Signac)
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Signac_1.0.0   devtools_2.3.2 usethis_1.6.3 

loaded via a namespace (and not attached):
  [1] reticulate_1.16             tidyselect_1.1.0            RSQLite_2.2.0              
  [4] AnnotationDbi_1.48.0        htmlwidgets_1.5.1           grid_3.6.3                 
  [7] BiocParallel_1.20.1         Rtsne_0.15                  munsell_0.5.0              
 [10] codetools_0.2-16            ica_1.0-2                   future_1.19.1              
 [13] miniUI_0.1.1.1              withr_2.3.0                 colorspace_1.4-1           
 [16] OrganismDbi_1.26.0          Biobase_2.46.0              knitr_1.29                 
 [19] rstudioapi_0.11             Seurat_3.2.2                stats4_3.6.3               
 [22] ROCR_1.0-11                 tensor_1.5                  listenv_0.8.0              
 [25] GenomeInfoDbData_1.2.2      polyclip_1.10-0             bit64_4.0.2                
 [28] rprojroot_1.3-2             vctrs_0.3.4                 generics_0.0.2             
 [31] xfun_0.16                   biovizBase_1.32.0           lsa_0.73.2                 
 [34] ggseqlogo_0.1               R6_2.4.1                    GenomeInfoDb_1.22.1        
 [37] rsvd_1.0.3                  AnnotationFilter_1.8.0      reshape_0.8.8              
 [40] bitops_1.0-6                spatstat.utils_1.17-0       DelayedArray_0.12.3        
 [43] assertthat_0.2.1            promises_1.1.1              scales_1.1.1               
 [46] nnet_7.3-14                 gtable_0.3.0                globals_0.13.0             
 [49] processx_3.4.4              goftest_1.2-2               ggbio_1.32.0               
 [52] ensembldb_2.8.1             rlang_0.4.7                 RcppRoll_0.3.0             
 [55] splines_3.6.3               rtracklayer_1.44.4          lazyeval_0.2.2             
 [58] dichromat_2.0-0             checkmate_2.0.0             BiocManager_1.30.10        
 [61] reshape2_1.4.4              abind_1.4-5                 GenomicFeatures_1.36.4     
 [64] backports_1.1.10            httpuv_1.5.4                qvalue_2.16.0              
 [67] Hmisc_4.4-1                 RBGL_1.60.0                 tools_3.6.3                
 [70] ggplot2_3.3.2               ellipsis_0.3.1              RColorBrewer_1.1-2         
 [73] BiocGenerics_0.32.0         sessioninfo_1.1.1           ggridges_0.5.2             
 [76] Rcpp_1.0.5                  plyr_1.8.6                  base64enc_0.1-3            
 [79] progress_1.2.2              zlibbioc_1.32.0             purrr_0.3.4                
 [82] RCurl_1.98-1.2              ps_1.3.4                    prettyunits_1.1.1          
 [85] rpart_4.1-15                deldir_0.1-29               pbapply_1.4-3              
 [88] cowplot_1.1.0               S4Vectors_0.24.4            zoo_1.8-8                  
 [91] SummarizedExperiment_1.16.1 ggrepel_0.8.2               cluster_2.1.0              
 [94] fs_1.5.0                    magrittr_1.5                data.table_1.13.0          
 [97] lmtest_0.9-38               RANN_2.6.1                  SnowballC_0.7.0            
[100] ProtGenerics_1.16.0         fitdistrplus_1.1-1          matrixStats_0.57.0         
[103] pkgload_1.1.0               hms_0.5.3                   patchwork_1.0.1            
[106] mime_0.9                    xtable_1.8-4                XML_3.99-0.3               
[109] jpeg_0.1-8.1                IRanges_2.20.2              gridExtra_2.3              
[112] testthat_2.3.2              compiler_3.6.3              biomaRt_2.40.5             
[115] tibble_3.0.3                KernSmooth_2.23-17          crayon_1.3.4               
[118] htmltools_0.5.0             mgcv_1.8-32                 later_1.1.0.1              
[121] Formula_1.2-3               tidyr_1.1.2                 DBI_1.1.0                  
[124] MASS_7.3-52                 rappdirs_0.3.1              Matrix_1.2-18              
[127] cli_2.0.2                   parallel_3.6.3              igraph_1.2.5               
[130] GenomicRanges_1.38.0        pkgconfig_2.0.3             GenomicAlignments_1.20.1   
[133] foreign_0.8-75              plotly_4.9.2.1              XVector_0.26.0             
[136] stringr_1.4.0               VariantAnnotation_1.30.1    callr_3.4.4                
[139] digest_0.6.25               sctransform_0.3             RcppAnnoy_0.0.16           
[142] graph_1.64.0                spatstat.data_1.4-3         Biostrings_2.52.0          
[145] fastmatch_1.1-0             leiden_0.3.3                htmlTable_2.0.1            
[148] uwot_0.1.8                  curl_4.3                    shiny_1.5.0                
[151] Rsamtools_2.0.3             lifecycle_0.2.0             nlme_3.1-149               
[154] jsonlite_1.7.1              desc_1.2.0                  viridisLite_0.3.0          
[157] BSgenome_1.52.0             fansi_0.4.1                 pillar_1.4.6               
[160] GGally_2.0.0                lattice_0.20-41             fastmap_1.0.1              
[163] httr_1.4.2                  pkgbuild_1.1.0              survival_3.2-3             
[166] glue_1.4.2                  remotes_2.2.0               spatstat_1.64-1            
[169] png_0.1-7                   bit_4.0.4                   stringi_1.5.3              
[172] blob_1.2.1                  latticeExtra_0.6-29         memoise_1.1.0              
[175] dplyr_1.0.2                 irlba_2.3.3                 future.apply_1.6.0         
```

**Comment by timoast** [comment]
You're installing from the main branch rather than the develop branch. See install instructions on the website: https://satijalab.org/signac/articles/install.html#development-version-1

**Comment by justin-malin** [comment]
Thanks. Got Signac_1.0.9001 installed now.

When I run my code (see above) from the beginning, I get:
```
> gr1 <- StringToGRanges(regions = rownames(pbmc.1.filtered), sep = c("-","-"))
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Signac/R/Signac.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1 
> pbmc.1.filtered
An object of class Seurat 
767681 features across 273 samples within 4 assays 
Active assay: reducedPeaks.WT.E15 (266110 features, 20000 variable features)
 3 other assays present: peaks, RNA, reducedPeaks.WT.KO
 2 dimensional reductions calculated: lsi, umap
```

**Comment by timoast** [comment]
You probably need to restart R

**Comment by justin-malin** [comment]
Yes. that worked.
 FindIntegrationAnchors goes farther than before but eventually throws an error
```
> anchors <- FindIntegrationAnchors(
+   object.list = list(pbmc.1.filtered, pbmc.2.filtered),
+   anchor.features = shared.features,
+   assay = c('peaks','peaks'),
+   k.filter = NA
+ )
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Error in CreateChromatinAssay(data = merged.data, min.cells = 0, min.features = 0,  : 
  Length of supplied genomic ranges does not match number
           of rows in matrix
```

**Comment by justin-malin** [comment]
For what it's worth, I was able to get FindIntegrationAnchors to work with this data in the earlier 0.2.5 version of signac.
However, at the time, I wasn't able to successfully integrate 3 datasets, which is ultimately my goal now.
Thanks,
Justin

**Comment by ninal88** [comment]
@justin-malin was this error fixed for you? because the develop version did not fix the problem for me

**Comment by timoast** [comment]
This seems to be a separate bug and also the cause of #230. I'll be taking a look today and see if I can fix it

**Comment by ninal88** [comment]
> This seems to be a separate bug and also the cause of #230. I'll be taking a look today and see if I can fix it

Thanks Tim! Appreciate it!

**Comment by timoast** [comment]
This was due to bugs in both Seurat and Signac. I've pushed fixes to the develop branch of both packages:

```r
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("timoast/signac", ref = "develop")
devtools::install_github("satijalab/seurat", def = "develop")
```
