### ISSUE TITLE
FindIntegrationAnchors()

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#289]
I am integrating 5 objects.  I added fragment assays to all objects. The features of each fragment assay are the common peaks among all objects.  I made sure each fragment assay had the same number of peaks. peaks.use (See "anchor.features =" argument) was the same length as the peaks I used for the assays.  I made sure to set default assay to fragment assay.  I made sure to get the development version of seurat and signac, that are bug fixed.  I still get this error

```
anchors <- FindIntegrationAnchors(
  object.list = object.list,
  anchor.features = GRangesToString(peaks.use),
  assay = rep("common.peak.assay", length(object.list)),
  k.filter = NA
)
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Error in SetAssayData.ChromatinAssay(object = new.assay, slot = "scale.data",  : 
  Number of rows in provided matrix is greater than
             the number of rows in the object
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
```

**Comment by timoast** [comment]
Please include the full code you're running ([formatted](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) correctly so it's readable), and the output of `sessionInfo()`

**Comment by danielcgingerich** [comment]
Hey Tim, I reformatted my code above.  Heres the full code: 
`library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(GenomicRanges)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(patchwork)
set.seed(1234)
memory.limit(24000)

#Load in the filtered datasets into .GlobalEnv: 
object.list <- list(1,2,3,4,5)
names(object.list) <- c("atac1099", "atac1557", "atac542", "atac347", "atac357")
number.list <- list("1099", "1557", "542", "347", "357")
for (i in 1:5) {
  object.list[[i]] <- readRDS(paste0('C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft (samples1099.1557.542.347.357)/',
                                     number.list[[i]],
                                     'atac_seurat.object_nucsig-tss-pct.reads-blacklist-filtered.rds'))
}

#Make it run faster. set forloop such that each sample gets around 500 cells.
#i added i^2.34343 just so each sample has diff # cells
cellset.list <- list(1,2,3,4,5)
for (i in 1:length(object.list)){
cellset.list[[i]] <- sample(colnames(object.list[[i]]), floor(500+i^2.3434))
object.list[[i]] <- SubsetData(object.list[[i]], cells = cellset.list[[i]])
}
list2env(object.list, envir = .GlobalEnv)

#Some basic object prep
for (i in 1:length(object.list)){
  object.list[[i]]$sample <- number.list[[i]]
  object.list[[i]] <- RunTFIDF(object.list[[i]])
  object.list[[i]] <- FindTopFeatures(object.list[[i]],
                                      min.cutoff = 50)
  object.list[[i]] <- RunSVD(object.list[[i]])
  object.list[[i]] <- RunUMAP(object.list[[i]], 
                              reduction = 'lsi',
                              dims = 2:30)
} 



#Peaks for integration: 
peak.list <- as.list(1:length(object.list))
for (i in 1:length(object.list)) {
  peak.list[[i]] <- StringToGRanges(rownames(object.list[[i]]), sep = c("-", "-"))
}
peaks.use <- Reduce(intersect, peak.list)
peaks.use <- sample(peaks.use, 5000)


#Make fragment assays with peaks.use and add to seuratobjects
common.peak.fragments.list <- as.list(1:length(object.list))
for (i in 1:length(object.list)){
  common.peak.fragments.list[[i]] <- FeatureMatrix(
      fragments = Fragments(object.list[[i]]),
      features = peaks.use,
      cells = colnames(object.list[[i]]))
  object.list[[i]][["common.peak.assay"]] <- CreateChromatinAssay(
      counts = common.peak.fragments.list[[i]],
      min.cells = -1,
      ranges = peaks.use,
      genome = 'hg38')
}

#Run TF-IDF on the new assays
for (i in 1:length(object.list)){
  DefaultAssay(object.list[[i]]) <- "common.peak.assay"
  object.list[[i]] <- RunTFIDF(object.list[[i]])
  
}

rm(atac1099, atac1557, atac347, atac357, atac542)
list2env(object.list, envir = .GlobalEnv)



#Integrate objecs using merged.peaks.assay
#Length of nrow(reduced.peak.assay)=length(reduced.peaks) for it to work
anchors <- FindIntegrationAnchors(
  object.list = object.list,
  anchor.features = GRangesToString(peaks.use),
  assay = rep("common.peak.assay", length(object.list)),
  k.filter = NA
)`

**Comment by danielcgingerich** [comment]
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] patchwork_1.0.1           ggplot2_3.3.2            
 [3] EnsDb.Hsapiens.v86_2.99.0 ensembldb_2.13.1         
 [5] AnnotationFilter_1.13.0   GenomicFeatures_1.41.2   
 [7] AnnotationDbi_1.51.1      Biobase_2.49.0           
 [9] GenomicRanges_1.41.5      GenomeInfoDb_1.25.8      
[11] IRanges_2.23.10           S4Vectors_0.27.12        
[13] BiocGenerics_0.35.4       Seurat_3.2.2.9005        
[15] Signac_1.0.9003          

loaded via a namespace (and not attached):
  [1] reticulate_1.16             tidyselect_1.1.0           
  [3] RSQLite_2.2.0               htmlwidgets_1.5.1          
  [5] grid_4.0.2                  BiocParallel_1.23.2        
  [7] Rtsne_0.15                  devtools_2.3.0             
  [9] munsell_0.5.0               codetools_0.2-16           
 [11] ica_1.0-2                   future_1.18.0              
 [13] miniUI_0.1.1.1              withr_2.2.0                
 [15] colorspace_1.4-1            OrganismDbi_1.31.1         
 [17] knitr_1.29                  rstudioapi_0.11            
 [19] ROCR_1.0-11                 tensor_1.5                 
 [21] listenv_0.8.0               GenomeInfoDbData_1.2.3     
 [23] polyclip_1.10-0             bit64_0.9-7                
 [25] rprojroot_1.3-2             vctrs_0.3.0                
 [27] generics_0.0.2              xfun_0.15                  
 [29] biovizBase_1.37.0           BiocFileCache_1.13.0       
 [31] lsa_0.73.2                  ggseqlogo_0.1              
 [33] R6_2.4.1                    rsvd_1.0.3                 
 [35] bitops_1.0-6                spatstat.utils_1.17-0      
 [37] reshape_0.8.8               DelayedArray_0.15.6        
 [39] assertthat_0.2.1            promises_1.1.1             
 [41] scales_1.1.1                nnet_7.3-14                
 [43] gtable_0.3.0                globals_0.12.5             
 [45] processx_3.4.3              goftest_1.2-2              
 [47] ggbio_1.37.0                rlang_0.4.6                
 [49] RcppRoll_0.3.0              splines_4.0.2              
 [51] rtracklayer_1.49.3          lazyeval_0.2.2             
 [53] dichromat_2.0-0             checkmate_2.0.0            
 [55] BiocManager_1.30.10         reshape2_1.4.4             
 [57] abind_1.4-5                 backports_1.1.8            
 [59] httpuv_1.5.4                Hmisc_4.4-1                
 [61] RBGL_1.65.0                 usethis_1.6.1              
 [63] tools_4.0.2                 ellipsis_0.3.1             
 [65] RColorBrewer_1.1-2          sessioninfo_1.1.1          
 [67] ggridges_0.5.2              Rcpp_1.0.5                 
 [69] plyr_1.8.6                  base64enc_0.1-3            
 [71] progress_1.2.2              zlibbioc_1.35.0            
 [73] purrr_0.3.4                 RCurl_1.98-1.2             
 [75] ps_1.3.3                    prettyunits_1.1.1          
 [77] rpart_4.1-15                openssl_1.4.2              
 [79] deldir_0.1-28               pbapply_1.4-2              
 [81] cowplot_1.0.0               zoo_1.8-8                  
 [83] SummarizedExperiment_1.19.5 ggrepel_0.8.2              
 [85] cluster_2.1.0               fs_1.4.2                   
 [87] magrittr_1.5                RSpectra_0.16-0            
 [89] data.table_1.12.8           lmtest_0.9-37              
 [91] RANN_2.6.1                  SnowballC_0.7.0            
 [93] ProtGenerics_1.21.0         fitdistrplus_1.1-1         
 [95] matrixStats_0.56.0          pkgload_1.1.0              
 [97] hms_0.5.3                   mime_0.9                   
 [99] xtable_1.8-4                XML_3.99-0.4               
[101] jpeg_0.1-8.1                gridExtra_2.3              
[103] shape_1.4.5                 testthat_2.3.2             
[105] compiler_4.0.2              biomaRt_2.45.2             
[107] tibble_3.0.1                KernSmooth_2.23-17         
[109] crayon_1.3.4                htmltools_0.5.0            
[111] mgcv_1.8-31                 later_1.1.0.1              
[113] Formula_1.2-3               tidyr_1.1.0                
[115] DBI_1.1.0                   dbplyr_1.4.4               
[117] MASS_7.3-51.6               rappdirs_0.3.1             
[119] Matrix_1.2-18               cli_2.0.2                  
[121] igraph_1.2.5                pkgconfig_2.0.3            
[123] GenomicAlignments_1.25.3    foreign_0.8-80             
[125] plotly_4.9.2.1              foreach_1.5.0              
[127] XVector_0.29.3              callr_3.4.3                
[129] stringr_1.4.0               VariantAnnotation_1.35.3   
[131] digest_0.6.25               sctransform_0.3.1          
[133] RcppAnnoy_0.0.16            graph_1.67.1               
[135] spatstat.data_1.4-3         Biostrings_2.57.2          
[137] leiden_0.3.3                fastmatch_1.1-0            
[139] htmlTable_2.1.0             uwot_0.1.8                 
[141] curl_4.3                    shiny_1.5.0                
[143] Rsamtools_2.5.3             lifecycle_0.2.0            
[145] nlme_3.1-148                jsonlite_1.7.0             
[147] desc_1.2.0                  fansi_0.4.1                
[149] viridisLite_0.3.0           askpass_1.1                
[151] BSgenome_1.57.6             pillar_1.4.4               
[153] lattice_0.20-41             GGally_2.0.0               
[155] pkgbuild_1.0.8              fastmap_1.0.1              
[157] httr_1.4.1                  survival_3.1-12            
[159] remotes_2.2.0               glue_1.4.1                 
[161] spatstat_1.64-1             png_0.1-7                  
[163] iterators_1.0.12            glmnet_4.0-2               
[165] bit_1.1-15.2                stringi_1.4.6              
[167] blob_1.2.1                  latticeExtra_0.6-29        
[169] memoise_1.1.0               dplyr_1.0.0                
[171] irlba_2.3.3                 future.apply_1.6.0         
```

**Comment by timoast** [comment]
What's the output of `length(intersect(GRangesToString(peaks.use), rownames(object.list[[1]])))`?

By the way, I'd highly recommend merging the objects first by following the [merge vignette](https://satijalab.org/signac/articles/merging.html) and assessing whether there are batch differences that need to be corrected, if you haven't done that already

**Comment by danielcgingerich** [comment]
Tim, 

With regards to your first question: 
length(intersect(GRangesToString(peaks.use), rownames(object.list[[1]])))
[1] 5000

I am currently working my way through the merge vignette.  I wanted to try Harmony instead and see if that worked.  I followed the merge vignette and I was not able to merge the objects.  The error is the same for `FindIntegrationAnchors()`.  Perhaps this may be a part of the problem?   Look: 

```
anchors <- FindIntegrationAnchors(
+   object.list = object.list,
+   anchor.features = GRangesToString(peaks.use),
+   assay = rep("common.peak.assay", length(object.list)),
+   k.filter = NA
+ )
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Error in SetAssayData.ChromatinAssay(object = new.assay, slot = "scale.data",  : 
  Number of rows in provided matrix is greater than
             the number of rows in the object
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
```

```
atac.merge <- merge(x = q.frag.seurat[[1]],
+                     y = list(q.frag.seurat[[2]],
+                              q.frag.seurat[[3]],
+                              q.frag.seurat[[4]],
+                              q.frag.seurat[[5]]))
Error in SetAssayData.ChromatinAssay(object = new.assay, slot = "data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object
```
```
c(nrow(q.frag.seurat[[1]]), nrow(q.frag.seurat[[2]]), nrow(q.frag.seurat[[3]]), nrow(q.frag.seurat[[4]]), nrow(q.frag.seurat[[5]]))
[1] 20000 20000 20000 20000 20000
```

**Comment by timoast** [comment]
This should be fixed now on the develop branch. Can you try again after installing from develop?

**Comment by danielcgingerich** [comment]
@timoast Thanks for getting back to me.  I will try it out soon and let you know!

**Comment by danielcgingerich** [comment]
@timoast I am sorry I still have not yet followed up, I still plan on getting back to you once I am less busy.  I have  ended up using a work-around method.  For anyone else still having this issue, I used RenameCells(object, add.cell.id=sample number) to add prefix to barcodes so I can tell what sample they are.  I used GetAssayData() to extract the matrices from my objects I planned to integrate.  Then I merged them using the Matrix.utils() package.  I converted back to a seurat object, added barcode prefixes to the metadata, and used RunHarmony() to integrate.
